const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 2,
      clientStars: 4,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_1.jpg',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      isCompare: false,
      image: '/images/beds/bed_2.jpg',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      isCompare: false,
      image: '/images/beds/bed_3.jpg',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_4.jpg',
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_5.jpg',
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_6.jpg',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_7.jpg',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_8.jpg',
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_9.jpg',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_10.jpg',
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_11.jpg',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_12.jpg',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_13.jpg',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_14.jpg',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_15.jpg',
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_16.jpg',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_17.jpg',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_18.jpg',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_19.jpg',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_20.jpg',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_21.jpg',
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_22.jpg',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_23.jpg',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
      image: '/images/beds/bed_24.jpg',
    },
  ],
  cart: {
    products: [],
  },
  advertisement: [
    {
      id: 1,
      panel: 'big',
      header: 'guest room',
      description: 'sofa',
      discount: '-20%',
    },
    {
      id: 2,
      panel: 'small top',
      header: '<span>Office</span> chair',
      description: 'collection',
      discount: '$200.00',
    },
    {
      id: 3,
      panel: 'small bottom',
      header: '<span>Special</span> collection',
      description: 'save up 45% of furniture',
      discount: '-',
    },
  ],
  brands: [
    {
      id: 1,
      logo: '/images/logos/logo1.png',
    },
    {
      id: 2,
      logo: '/images/logos/logo2.jpg',
    },
    {
      id: 3,
      logo: '/images/logos/logo3.jpg',
    },
    {
      id: 4,
      logo: '/images/logos/logo4.png',
    },
    {
      id: 5,
      logo: '/images/logos/logo5.jpg',
    },
    {
      id: 6,
      logo: '/images/logos/logo6.png',
    },
    {
      id: 7,
      logo: '/images/logos/logo7.jpg',
    },
    {
      id: 8,
      logo: '/images/logos/logo8.jpg',
    },
    {
      id: 9,
      logo: '/images/logos/logo9.png',
    },
    {
      id: 10,
      logo: '/images/logos/logo10.png',
    },
    {
      id: 11,
      logo: '/images/logos/logo11.jpg',
    },
    {
      id: 12,
      logo: '/images/logos/logo12.png',
    },
    {
      id: 13,
      logo: '/images/logos/logo13.jpg',
    },
    {
      id: 14,
      logo: '/images/logos/logo14.png',
    },
  ],
  feedback: [
    {
      name: 'John Smith',
      position: 'Marketing Manager',
      photo:
        'https://images.pexels.com/photos/1933873/pexels-photo-1933873.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      quote:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nulla maximus, rhoncus nibh ac, tempor erat. Nunc et odio eget justo porta porta. Praesent pharetra lorem porta eros varius tempor. Phasellus vitae urna neque. Sed semper elementum nunc, aliquet faucibus eros sagittis non. Aenean egestas dui eget sapien mattis lacinia. Duis ante est, rutrum ut arcu ut, condimentum scelerisque ipsum.',
    },
  ],
};

export default initialState;
